/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedLibrarianRouteImport } from './routes/_authenticated.librarian'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedPaperIdRouteImport } from './routes/_authenticated.paper.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibrarianRoute = AuthenticatedLibrarianRouteImport.update({
  id: '/librarian',
  path: '/librarian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaperIdRoute = AuthenticatedPaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/librarian': typeof AuthenticatedLibrarianRoute
  '/search': typeof AuthenticatedSearchRoute
  '/paper/$id': typeof AuthenticatedPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/librarian': typeof AuthenticatedLibrarianRoute
  '/search': typeof AuthenticatedSearchRoute
  '/paper/$id': typeof AuthenticatedPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/librarian': typeof AuthenticatedLibrarianRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/paper/$id': typeof AuthenticatedPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/librarian' | '/search' | '/paper/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/librarian' | '/search' | '/paper/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/librarian'
    | '/_authenticated/search'
    | '/_authenticated/paper/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/librarian': {
      id: '/_authenticated/librarian'
      path: '/librarian'
      fullPath: '/librarian'
      preLoaderRoute: typeof AuthenticatedLibrarianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paper/$id': {
      id: '/_authenticated/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof AuthenticatedPaperIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibrarianRoute: typeof AuthenticatedLibrarianRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedPaperIdRoute: typeof AuthenticatedPaperIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibrarianRoute: AuthenticatedLibrarianRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedPaperIdRoute: AuthenticatedPaperIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
